### PR TITLE
Update cf-operator dependency.

### PR DESCRIPTION
**Pull request by cfcontainerizationbot**
Increment cf-operator version in def.bzl file.

### CODE REVIEW

**Comment by mook-as** [comment]
Taking this PR: I'm doing #564 anyway, which this will obsolete (so I'm just combining the two).

**Comment by mook-as** [comment]
It looks like cf-operator doesn't handle this correctly (the old qsts isn't removed); filed https://github.com/cloudfoundry-incubator/cf-operator/issues/877.

**Comment by mook-as** [comment]
The smoke tests are failing because the test scripts assume the prefix; https://github.com/SUSE/catapult/pull/151 created.

**Comment by mudler** [comment]
I've just triggered one CI run with the catapult version pinned to the PR from @mook-as, let's see how it goes https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/deploy-diego/builds/369

**Comment by mudler** [comment]
Seems something is wrong with the changes to test triggers: https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-diego/builds/136

```
[backend/check.sh] [backend:imported] [cluster:kind-MTZmNzM4NTdlNWQxNWQ1ZjVhODFlZTVi] k8s cluster imported successfully

make -s -C modules/tests kubecf

/tmp/build/fd3e545c/catapult/buildkind-MTZmNzM4NTdlNWQxNWQ1ZjVhODFlZTVi /tmp/build/fd3e545c/catapult/modules/tests

[./kubecf-test.sh] [backend:imported] [cluster:kind-MTZmNzM4NTdlNWQxNWQ1ZjVhODFlZTVi] Loading

job.batch "susecf-scf-smoke-tests-050c59d67ab5541f" deleted

Error from server: Invalid JSON Patch

make[1]: *** [Makefile:49: kubecf] Error 1

make: *** [Makefile:271: tests-kubecf] Error 2
```

**Pull request merged**
