### PR TITLE
feat: add klog.sh to the bundle

### PR DESCRIPTION
**Pull request by f0rmiga**

### CODE REVIEW

**Comment by f0rmiga** [comment]
I'll mark this PR ready, and you guys merge whenever you want.

**Comment by fargozhu** [comment]
> @fargozhu Is there a point in reviewing this draft PR yet? It looks small enough that it seems unlikely to need major changes before it becomes non-draft.

sorry I miss the gray colour...

**Comment by jandubois** [comment]
@troytop and @gaktive decided that this change is not needed/wanted:

>as long as it's downloadable from somewhere public so that people can get the tool if they need it

**Comment by troytop** [comment]
To clarify, there's nothing wrong with including this (i.e. the commit is fine), but it's not _required_ for the upcoming release (i.e. OK to reject this PR).

**Pull request closed without merging**
