### PR TITLE
Fix the eirini ssh service

### PR DESCRIPTION
**Pull request by viovanov**
## Description
The SSH service had the wring ports configured.

## Motivation and Context
ssh to app with Eirini should work

## How Has This Been Tested?
Tested locally.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by f0rmiga** [comment]
@viovanov Removing the port 443 is wrong. I get this right away:
```
LAST SEEN   TYPE      REASON         OBJECT                                     MESSAGE
61s         Warning   FailedCreate   job/8d711400-98e3-4719-94ac-4a102c1c8206   Error creating: Internal error occurred: failed calling webhook "0.eirini-ssh.org": Post https://kubecf-eirini-ssh.kubecf.svc:443/0?timeout=30s: no service port 'ƻ' found for service "kubecf-eirini-ssh"
```

Since this is an eirini extension, it should expose port 443 for the webhook.

**Comment by f0rmiga** [comment]
@viovanov Reading the Eirini pieces better, there are 2 jobs related to SSH, one is the ssh-extension (the one you changed the port) and the ssh-proxy. We want to expose the ssh-proxy as well and leave the ssh-extension as it was before.

**Comment by f0rmiga** [comment]
I see that we already expose the ssh-proxy port in the same way we do with diego. The problem is something else:

```
{"timestamp":"1583785022.329963684","source":"ssh-proxy","message":"ssh-proxy.authentication-failed","log_level":2,"data":{"error":"ssh: no auth passed yet","user":"cf:9f356664-8c88-4892-aabc-87c09ed9676f/0"}}
{"timestamp":"1583785022.330345631","source":"ssh-proxy","message":"ssh-proxy.cf-authenticate.authenticate-starting","log_level":1,"data":{"session":"8"}}
{"timestamp":"1583785022.531857491","source":"ssh-proxy","message":"ssh-proxy.cf-authenticate.app-access-success","log_level":1,"data":{"app":"9f356664-8c88-4892-aabc-87c09ed9676f/0","principal":"20442c4a-d21e-40e3-8b16-f53b23a838e8","session":"8","username":"admin"}}
{"timestamp":"1583785022.531913996","source":"ssh-proxy","message":"ssh-proxy.cf-authenticate.authenticate-finished","log_level":1,"data":{"session":"8"}}
{"timestamp":"1583785022.531944990","source":"ssh-proxy","message":"ssh-proxy.authentication-attempted","log_level":1,"data":{"user":"cf:9f356664-8c88-4892-aabc-87c09ed9676f/0"}}
{"timestamp":"1583785022.532186270","source":"ssh-proxy","message":"ssh-proxy.handle-connection.new-client-conn.dial-failed","log_level":2,"data":{"address":"10.244.0.61:2222","error":"dial tcp 10.244.0.61:2222: connect: connection refused","session":"7.1"}}
```

The failure is on ssh-proxy trying to connect to the app pod.

@jimmykarily Could probably shed some light here.

**Comment by jimmykarily** [comment]
If the eirinifs is not our SLE version then it is not running the sshd daemon and thus the proxy can't connect to it. What stack are you using for the app?

**Comment by f0rmiga** [comment]
Closing this in favour of https://github.com/cloudfoundry-incubator/kubecf/issues/476.

**Comment by viovanov** [comment]
@f0rmiga we should've merged this anyway - the current service makes no sense

**Comment by f0rmiga** [comment]
@viovanov It does. It's the mutating admission webhook. Without it, Eirini stops working completely.

**Pull request closed without merging**
