### PR TITLE
Updated the eirinix to re-introduce the ssh-proxy fixes.

### PR DESCRIPTION
**Pull request by andreas-kupries**
## Description

This brings back the local #1027 changes which were lost with #1077 updating the sub charts.

## Motivation and Context

See the above referenced PR's for the context.
Note further that this fix should obviate the need for #1118 

## How Has This Been Tested?

It will be tested through the CI (eirini smoke tests)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
@jimmykarily @viovanov  :warning: :warning: :warning: This is not complete yet, and has issues.

  1. The lint failed, see below. Not investigated why yet, it is EOD/EOW.
  1. The https://github.com/SUSE/eirinix-helm-release/pull/13 fixed only the ssh-proxy template, the values.yaml was forgotten.
  1. The https://github.com/SUSE/eirinix-helm-release/pull/14 has the changes to the `values.yaml`, but looks incorrect.
      The original PR #1027 used an explicit version tag for the ssh docker image in the sub chart values.yaml.
      And right now the PR 14 has the pinned image version directly added to it. This likely will not work.

      Because in the `eirinix-helm-release` chart the relevant `values.yaml` has `latest` everywhere for all the tags and
      the https://concourse.suse.dev/teams/main/pipelines/eirinix pipeline replaces that with proper tags.
      The pipeline uses the resource https://concourse.suse.dev/teams/main/pipelines/eirinix/resources/s3.ssh-version
      to determine the version tag to use in the replacement.

     This resource has the tag we want (`v0.0.0-0.g04a3871`), but picks the older tag (`v0.0.0-0.ge2ed1ab`) somehow.
     (I suspect it is a sorting issue on the filenames)

**Comment by jandubois** [comment]
> 1. The lint failed, see below. Not investigated why yet, it is EOD/EOW.

It fails because https://github.com/SUSE/eirinix-helm-release/pull/13/files is missing an `{{- end }}` line at the bottom, to close the `{{- with ... }}` block.

**Comment by andreas-kupries** [comment]
Fixed the missing `{{- end}}` in https://github.com/SUSE/eirinix-helm-release/pull/14.
Seeing conflicts I will also rebase this one.

**Comment by andreas-kupries** [comment]
@jandubois 

Pushed a rebase to undo the #1118 revert while keeping the #1027 work.

This still has some manual fixups for that until https://github.com/SUSE/eirinix-helm-release/pull/14 is properly done, including having resolved with @viovanov and @jimmykarily how to fix the image tagging for that.

That said, with the manual fixups we should be able to run it through CI and see if that
  1. fixes the ssh-proxy, and
  2. the smoke tests.

For that I require a new approval.

**Comment by jimmykarily** [comment]
I think what [the eirinix pipeline](https://concourse.suse.dev/teams/main/pipelines/eirinix) is doing to replace "latest" with proper tags is a bit error prone. When one wants to replace "latest" with whatever tag equals to "latest" they should pull "latest" and then either find the relevant tag in some metadata (if that is available) or simply replace with the digest version. The way we do it we introduced one more moving part which is the s3 file.

In any case, if we fixed the versioning of the various components and started releasing with at least patch versions and not `v0.0.0-some-prerelease-thing-here` sorting would work and all things would be good as they are now. Should I open an issue to change versioning of components to use the patch part instead of pre-release?

**Comment by andreas-kupries** [comment]
@jandubois @jimmykarily That sounds good. Please make sure that the new issue is high-priority, as the versioning stuff here blocks not just this, but #1077 / #819 as well.

Do you know who would have the best knowledge of the pipeline to work on this ?

**Pull request closed without merging**
