### PR TITLE
wip: bump cf-deployment to 15.1.0

### LINKED ISSUE #1584: Bump to cf-deployment to 15.0
https://github.com/cloudfoundry/cf-deployment/releases/tag/v15.0.0 became available in the first week of November. 

kubecf is presently at `13.17`. As of `14.0`, there were breaking changes tied to certificates. Do note that the versioning went from 14.0 to 15.0 without minor versions and the final 13 release is `13.23`.

We've had one request for an updated nats-release, which ties into some updates found in `14.0` tied to improved health checks: https://github.com/cloudfoundry/nats-release/releases/tag/v38

### PR DESCRIPTION
**Pull request by jandubois**
🚧 Do not merge; this PR only exists to run the code through CI 🚧 

Fixes #1584

### CODE REVIEW

**Review by mook-as — APPROVED** [review]

**Review by andreas-kupries — DISMISSED** [review]
:+1:

**Review by mook-as — APPROVED** [review]

**Review by andreas-kupries — APPROVED** [review]

**Comment by mook-as** [comment]
This is failing in smoke-tests-eirini because we need to bump Eirini to at least 2.0.0 for this cf-deployment.

**Comment by jandubois** [comment]
Bumping cf-deployment is blocked unless we either drop support for Eirini, or bump to Eirini 2+ (which no longer supports what the Eirini team now calls "legacy staging", i.e. staging using the CF buildpacks).

**Comment by jandubois** [comment]
Re-opening for investigative reasons only

**Pull request closed without merging**
