### PR TITLE
feat: bump eirini to 1.8.0

### LINKED ISSUE #843: Bump to latest Eirini
## Acceptance Criteria

- [ ] newer Eirini docker images
- [ ] newer Bits docker images
- [x] latest helm chart for Eirini (done as part of #1179)
- [x] latest helm chart for Bits (done as part of #1179)
- [ ] don't degrade working cats

### PR DESCRIPTION
**Pull request by viovanov**
## Description
Bumps eirini and bits.

## Motivation and Context
Fixes #843

## How Has This Been Tested?
Locally. Might need some fixes to the logging bridge.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by viovanov** [comment]
@mudler please base your work for #1037 on this

**Review by jandubois — DISMISSED** [review]
I've tested the PR on minikube:

There are no logs during staging. However, both `cf logs` and `cf logs --recent` seem to work for the runtime logs.

SSH has also been broken:

```
$ cf ssh 12factor
FAILED
Error: SSH session allocation failed: ssh: unexpected packet in response to channel open: <nil>
```

Both staging logs and app ssh worked before this PR.

**Review by mudler — DISMISSED** [review]
Let the CI :factory_worker: test it

**Comment by mudler** [comment]
Eirini CI is happy! :tada:

**Review by mudler — APPROVED** [review]

**Pull request merged**
