### PR TITLE
Upstream patch for opi BPM

### PR DESCRIPTION
**Pull request by f0rmiga**
Ties to https://github.com/cloudfoundry-community/eirini-bosh-release/pull/69.

Part of the effort to upstream patches we currently have on kubecf - https://github.com/SUSE/kubecf/issues/12.

### CODE REVIEW

**Comment by viovanov** [comment]
@jimmykarily how hard would it be to get this in the eirini BOSH release?

**Comment by viovanov** [comment]
@f0rmiga if that gets merged, wouldn't we remove the patch altogether?

**Comment by f0rmiga** [comment]
@viovanov Yes. In any case, I wanted to have this merged here so we don't get confused about differences in what we have in the patch and what we have upstream as a PR.

**Comment by viovanov** [comment]
The eirini bosh relese is becoming obsolete because of #651

**Pull request closed without merging**
