### PR TITLE
fix: update azs ops file to set availability zone when multi_az is enabled

### PR DESCRIPTION
**Pull request by aqan213**
## Description
Recreate the PR for https://github.com/cloudfoundry-incubator/kubecf/pull/1244

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aqan213** [comment]
@viovanov Sorry. I closed the PR #1244 by mistake and all changes are gone. So I reopened the new PR. Can you please help to review this one?

**Comment by viovanov** [comment]
@aqan213 can you please rebase this?

**Comment by aqan213** [comment]
@viovanov I have rebase it to the master. thanks,

**Review by viovanov — DISMISSED** [review]

**Comment by viovanov** [comment]
@aqan213 can you please fix your CLA?

**Comment by jandubois** [comment]
Closing (and re-opening) to see if it triggers EasyCLA to recheck

**Comment by jandubois** [comment]
@aqan213 please fix the CLA authorization (there is a link in the [CLA bot message](https://github.com/cloudfoundry-incubator/kubecf/pull/1472#issuecomment-758691542) above. When the CF Foundation merged into the Linux Foundation, all CLAs had to be re-affirmed... The bot just confirmed that you are still not authorized.

@andrew-edgar If @aqan213 no longer works on this project, but IBM still wants to get this PR applied, please re-submit it using a Github account that has CLA authorization.

**Comment by jandubois** [comment]
> @andrew-edgar If @aqan213 no longer works on this project, but IBM still wants to get this PR applied, please re-submit it using a Github account that has CLA authorization.

@andrew-edgar has confirmed on Slack that I should close this PR, and somebody else with a current CLA will re-create the PR again in the future.

**Pull request closed without merging**
