### PR TITLE
CI: Ensure cluster resources between pipelines don't collide

### PR DESCRIPTION
**Pull request by viccuad**
## Description

Ensure cluster resources between pipelines don't collide:

* Namespace gke cluster names with the pipeline name
  For this, add new pipeline option `resource_prefix: kubecf`
  This option prefixes the cluster names, and allows to deploy copies of the
pipeline for development.

* Remove `kubecf-ci` from GKE cluster names, or they get truncated
   GKE cluster names get truncated at around ~14 chars. We use them as a poor-man
substitute for atomic pools. Remove `kubecf-ci` prefix on the GKE cluster names,
so clusters like `kubecf-ci-kubecfmaster`, `kubecf-ci-release-2.3`,
`kubecf-ci-release-2.2` don't get truncated to `kubecf-ci-rele`, losing the
atomicity.

## Motivation and Context

Closes https://github.com/cloudfoundry-incubator/kubecf/issues/1095 (be able to deploy pipelines from the branch code, not from master).

This change is needed because we are not using an atomic pool. Can be removed once we have one.

## How Has This Been Tested?

https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad2

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by viccuad** [comment]
Marking the PR as WIP (don't have rights to make it draft).

upgrade-task fails, https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad2/jobs/upgrade-test-viccuad-atomic-gkename/builds/1

**Comment by viccuad** [comment]
Also fails when `resource_prefix` is too long: https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad2/jobs/deploy-diego-viccuad-atomic-gkename/builds/1#L5f032eda:44

**Comment by viccuad** [comment]
Force-pushed with fix by truncating gke cluster names and passing the correct gke cluster name to the upgrade task.

Example pipeline running on: https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad2/jobs/upgrade-test-viccuad-atomic-gkename/builds/2
- see the `semver.gke-cluster-kubecf-viccu-viccuad-atom-upgrade` resource inside the build runs, which is atomic to each deployed pipeline and the branch it tests.

To fill the github statuses for this PR, this PR should get an approved review, for the PR to get put on the queue in https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad2/resources/kubecf-pr. Once that happens, the 1108 PR can be pinned there, and the lint-pr job unpaused for all the pipeline to test the PR and report back the status.

**Comment by viccuad** [comment]
Thins to look for to approve the PR:
- cluster creation works (see deploy-diego for example https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad2/jobs/deploy-diego-viccuad-atomic-gkename/builds/9)
- passing a cluster between deploy and test jobs works
- cluster cleanup works (see the cleanup after the upgrade for example https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad2/jobs/upgrade-test-viccuad-atomic-gkename/builds/3)

**Comment by prabalsharma** [comment]
@viccuad I am wondering why did we not just work on https://github.com/cloudfoundry-incubator/kubecf/issues/1078 to resolve this issue?

**Comment by prabalsharma** [comment]
Testing notes:
https://concourse.suse.dev/teams/main/pipelines/1108-kubecf

```
  resource semver.gke-cluster-master-diego has been removed:
- name: semver.gke-cluster-master-diego
- source:
-   access_key_id: ((aws-access-key))
-   bucket: prabal-kubecf-ci
-   driver: s3
-   initial_version: 0.0.1
-   key: gke-cluster-master-diego
-   region_name: us-west-2
-   secret_access_key: ((aws-secret-key))
- type: semver

  resource semver.gke-cluster-1108-master-diego has been added:
+ name: semver.gke-cluster-1108-master-diego
+ source:
+   access_key_id: ((aws-access-key))
+   bucket: prabal-kubecf-ci
+   driver: s3
+   initial_version: 0.0.1
+   key: gke-cluster-master-diego
+   region_name: us-west-2
+   secret_access_key: ((aws-secret-key))
+ type: semver
```

```
-               export GKE_CLUSTER_NAME="kubecf-ci-${BRANCH//./-}-${CFSCHEDULER//./-}-$(cat semver.gke-cluster/version | sed 's/\./-/g')"
+               export GKE_CLUSTER_NAME="1108-${BRANCH//./-}-${CFSCHEDULER//./-}-$(cat semver.gke-cluster/version | sed 's/\./-/g')"
```

```
-           semver.gke-cluster: semver.gke-cluster-master-diego
+           semver.gke-cluster: semver.gke-cluster-1108-master-diego
```

```
job upgrade-test-pr has changed:
+     RESOURCE_PREFIX: "1108"
```

```
  job upgrade-test-master has changed:
+     RESOURCE_PREFIX: "1108"
```
Could not run the CI as Concourse complains about `no workers`

**Comment by viccuad** [comment]
> @viccuad I am wondering why did we not just work on #1078 to resolve this issue?

because this PR is part of https://github.com/cloudfoundry-incubator/kubecf/issues/1095, a story to ensure that pipelines don't clash with each other, and minimally backport changes to release-2.3 branch to fix that pipeline. Right now, without this PR, cluster names could clash between the `kubecf` pipeline pr tab, and the `kubecf-release-2.3` pipeline pr tab.

I opted to work on a minimal bugfix. #1078 entails a big refactor that historically has taken us at least a week to achieve. And we need to release a 2.3 at the end of the sprint, and not have breakage for us and our contributors.

> Testing notes:
> https://concourse.suse.dev/teams/main/pipelines/1108-kubecf

Pipeline is running now, but it seems to be following the `master` branch. Hence, the upgrade job doesn't contain the bugfix of this PR, their cluster names are in the form of `kubecf-ci-master-upgrade-0-0-2`, which could clash with current master and release-2.3 pipelines. I have paused the upgrade job.

**Comment by viccuad** [comment]
testing (and updating the github statuses) here: https://concourse.suse.dev/teams/main/pipelines/kubecf-viccuad2?group=pr

**Comment by viccuad** [comment]
This can be merged already, as it deletes clusters correctly. and we don't need the full suite of tests for this PR.

**Pull request merged**
