### PR TITLE
fix: Actually run CATS with eirini config in CI

### PR DESCRIPTION
**Pull request by viccuad**
## Description

Actually run CATS with eirini config in CI. We were using the default config of cats with `KUBECF_TEST_SUITE=cats`.
We should be using `KUBECF_TEST_SUITE=cats-eirini`, which will patch the cats config.

## How Has This Been Tested?

Running locally with `KUBECF_TEST_SUITE=cats-eirini`, and attempting to fly the pipeline (without flying) to see that the change only affects the `cf-acceptance-tests-eirini-*` jobs in concourse.  

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by jbuns — APPROVED** [review]
LGTM

**Comment by viccuad** [comment]
Pipeline flown already, linting errors are not from this PR, they seem to come from https://github.com/cloudfoundry-incubator/kubecf/pull/1317/checks?check_run_id=1102304242

**Comment by viccuad** [comment]
Rebased on top of master to fix lint errors.

**Review by jbuns — APPROVED** [review]
LGTM

**Comment by viccuad** [comment]
Job https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-eirini-master/builds/29 is also running with this settings, as the changes are already flown

**Pull request merged**
