### PR TITLE
Only test PRs open against master branch

### PR DESCRIPTION
**Pull request by viccuad**
## Description

If we leave testing PRs open against all branches, it will test PRs against
release branches. Those are:
- ensured to fail, since they don't have the bash-is-beautiful build system for
example
- already being tested correctly in their respective release pipelines

## Motivation and Context

Needed by https://github.com/cloudfoundry-incubator/kubecf/issues/1095

## How Has This Been Tested?

When we added the config option.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by viccuad** [comment]
flown.

**Comment by jandubois** [comment]
@viccuad 

> If we leave testing PRs open against all branches, it will test PRs against
> release branches. Those are:
> 
> * ensured to fail, since they don't have the bash-is-beautiful build system for
>   example

That should be a temporary problem only.

> * already being tested correctly in their respective release pipelines

I don't understand this argument. Which pipelines are testing PRs against release branches? If you mean the release branch pipelines themselves, then they are running too late. Nothing should be merged into a release branch that hasn't passed CI.

Isn't this argument the same as saying there is no need to tests PRs against master either, as all master PRs will be tested by the master pipeline?

**Comment by viccuad** [comment]
> That should be a temporary problem only.

Sadly, it's not temporary. We need pipelines deployed from the respective branches: `release2-2`, `release-2.3`, etc will never be bazel-less, will have a different set of prod and experimental jobs, and different set of tests.

(See linked catch-all issue https://github.com/cloudfoundry-incubator/kubecf/issues/1095)

> Isn't this argument the same as saying there is no need to tests PRs against master either, as all master PRs will be tested by the master pipeline?

No. In the future we will have a `release-X.Y` pipeline, that both tests PRs against `release-X.Y`, and continuosly the branch, for being able to cut a release. 
This PR we are commenting on is to make the master `kubecf` pipeline not double-test the PRs opened against `release-X.Y`.

**Comment by jandubois** [comment]
> In the future we will have a `release-X.Y` pipeline, that both tests PRs against `release-X.Y`, and continuosly the branch, for being able to cut a release.

Ok, that is even better. I wasn't aware that the release pipelines would also test PRs and not just the merged state (as they are now). Happy to see the direction this is moving!

**Pull request merged**
