### PR TITLE
fix: check for stemcell semver

### PR DESCRIPTION
**Pull request by bikramnehra**
## Description

This PR adds functionality to only update stemcell version if its higher than existing. 

## Motivation and Context

We recently saw issues in `fissile-stemcell-sle` versions not appearing in order in : https://hub.docker.com/repository/docker/splatform/fissile-stemcell-sle

## How Has This Been Tested?

Test pipelines deployed at concourse.suse.dev.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by f0rmiga** [comment]
Any chance we could use https://pypi.org/project/semver/ instead?

**Comment by bikramnehra** [comment]
> Any chance we could use https://pypi.org/project/semver/ instead?

I don't think the comparison we are doing is following proper `MAJOR.MINOR.PATCH` versioning which is required by [semver](https://pypi.org/project/semver/).

```
>>> semver.VersionInfo.isvalid("23.20")
False
```

Though we can override it but it might be an overkill.

**Comment by jandubois** [comment]
How about using `Gem::Version` then?

```
$ ruby -e "exit Gem::Version.new('20.33') < Gem::Version.new('20.222')"; echo $?
0
$ ruby -e "exit Gem::Version.new('20.33') < Gem::Version.new('20.2')"; echo $?
1
```

I also generally prefer to keep all scripts to either shell or ruby and not add more and more languages to the mix.

**Comment by bikramnehra** [comment]
I was able to use `semver` with a little trick.

**Pull request merged**
