### PR TITLE
Bump CATs release to get proper exit codes

### PR DESCRIPTION
**Pull request by mudler**
https://github.com/SUSE/cf-acceptance-tests-release/commit/187c3c624e314e63cc5b32164576cce2793a2743

Signed-off-by: Dimitris Karakasilis <DKarakasilis@suse.com>

## Description
The cleanup trap hides the exit code in case of failures

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by f0rmiga** [comment]
@mudler The image doesn't seem to be published?

**Comment by mudler** [comment]
Pretty sure we triggered the pipeline.. but maybe we have missed something ?

**Comment by jimmykarily** [comment]
0.0.11 was build and pushed here: https://ci.flintstone.cf.cloud.ibm.com/teams/quarks/pipelines/release-images/jobs/build-cf-acceptance-tests/builds/19 Maybe the tag is not constructed correctly?

**Comment by jimmykarily** [comment]
We need to bump the stemcell for this to work (see some lines above the change

**Comment by f0rmiga** [comment]
@mudler @jimmykarily It's good to bump the default stemcell, but it carries more responsibility of testing that all the releases that depend on the default stemcell still works correctly.

**Comment by jimmykarily** [comment]
Is there a way to bump the cats release without bumping all? If not, is CATs and smoke tests enough to give us confidence to merge?

**Comment by f0rmiga** [comment]
@jimmykarily Yes, you can set a specific stemcell for CATS like this: https://github.com/cloudfoundry-incubator/kubecf/blob/master/deploy/helm/kubecf/values.yaml#L85-L87.

I'd prefer to bump only the CATS stemcell and have another task to bump the default one. Smoke and CATS are not testing all the releases at this point, unfortunately.

**Comment by jimmykarily** [comment]
Nice thanks! I pushed a commit to only bump the cats stemcell. Let's see what the CI has to say.

**Comment by f0rmiga** [comment]
CATS failed twice with this PR on my local testing. Both run with flake attempts set to 2.

**Comment by mudler** [comment]
Deployment seems to fail as in master.. can't tell if it's related to our bump

**Comment by jimmykarily** [comment]
Passed tests: https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-diego/builds/35

**Pull request merged**
